### ISSUE TITLE
[MUI] Date expired of license 

### ISSUE THREAD

**Issue by thaonguyennv** [thaonguyennv/Car_Rental#38]
Các bằng lái có hạn là 5 or 10 năm
1. Nên cho Date expried chọn năm thôi cũng đc, có 2 option: 5 năm/10 năm.
2. Cho scroll năm xa xa tý, 10 năm là tới 2029 lận

**Comment by kokorolee** [comment]
https://github.com/thaonguyennv/Car_Rental/pull/44
